config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :achievements
  resources :notes
  resources :lessons
  resources :courses
  resources :charges

  authenticated :user do
    #root to: 'courses#index', :as => "authenticated_root"
    #in the meantime, a welcome route
    root to: 'courses#index', :as => "authenticated_root"
  end

  root to: 'visitors#home'
  
  devise_for :users
  resources :users

  get "about" => "visitors#about"

  #in order to make stripe work
  post '/buy/:id', to: 'charges#create', as: :buy
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :subscriber, :class_name => "User"
	belongs_to :course
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:new, :index, :edit, :update, :show]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:subscriber_id, :course_id, :stripe_id, :charge_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  
    <%= f.collection_select :subscriber_id, User.all, :id, :email, {prompt: false}, {class: "form-control input-lg"} %>
    <br>
    <%= f.collection_select :course_id, Course.all, :id, :name, {prompt: false}, {class: "form-control input-lg"} %>
  <br>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Subscriber</th>
      <th>Course</th>
      <th>Stripe id</th>
      <th>Charge id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.subscriber_id %></td>
        <td><%= subscription.course_id %></td>
        <td><%= subscription.stripe_id %></td> -
        <td><%= subscription.charge_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subscriber:</strong>
  <%= @subscription.subscriber_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @subscription.course_id %>
</p>

<p>
  <strong>Stripe:</strong>
  <%= @subscription.stripe_id %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @subscription.charge_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>