config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :achievements
  resources :notes
  resources :lessons
  resources :courses
  resources :charges

  authenticated :user do
    #root to: 'courses#index', :as => "authenticated_root"
    #in the meantime, a welcome route
    root to: 'courses#index', :as => "authenticated_root"
  end

  root to: 'visitors#home'
  
  devise_for :users
  resources :users

  get "about" => "visitors#about"

  #in order to make stripe work
  post '/buy/:id', to: 'charges#create', as: :buy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :course
	has_many :notes
	has_many :achievements, :as => :achievable

	def to_param
	    "#{id} #{name}".parameterize
	end

	def previous
	  Lesson.where(:course_id => self.course_id).where(["nr < ?", nr]).last
	end

	def next
	  Lesson.where(:course_id => self.course_id).where(["nr > ?", nr]).first
	end

	auto_html_for :video do
      html_escape
      image
      youtube(:width => 725, :height => 450, :autoplay => true)
      vimeo(:width => 725, :height => 450, :autoplay => true)
      link :target => "_blank", :rel => "nofollow"
      simple_format
    end

    def duration_in_minutes
    	(duration / 60).round
    end

    def seconds_left
		duration - (duration_in_minutes*60)
	end

	def display_duration
		if duration_in_minutes >= 1
			"#{duration_in_minutes}'#{seconds_left}''"
		else
			"#{duration_in_seconds}''"
		end
	end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :student_only, only: [:show]
  before_action :admin_only, only: [:new, :create, :update, :index]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @notes = @lesson.notes
    @note = Note.new
    @achievement = current_user.achievements.build
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def student_only
      @lesson = Lesson.find(params[:id])
      if current_user
        redirect_to course_path(@lesson.course), notice: "Vous devez vous inscrire à ce cours pour suivre la leçon" if !current_user.is_student?(@lesson.course)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name, :description, :nr, :video, :course_id, :duration)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.collection_select :course_id, Course.all, :id, :name, {prompt: false}, {class: "form-control input-lg"} %>
    <br>
    <div class="row">
      <div class="col-md-3">
        <%= f.text_field :nr, :placeholder => "numéro", class: "form-control input-lg" %>
      </div>
      <div class="col-md-9">
        <%= f.text_field :name, :placeholder => "Nom de la leçon", class: "form-control input-lg" %>
      </div>
  </div>
  <br>
    <%= f.text_area :description, :placeholder => "Description de la leçon", class: "form-control input-lg" %>
    <br>
    
    <div class="row">
      <div class="col-md-8">
        <%= f.text_field :video, :placeholder => "lien vidéo de la leçon", class: "form-control input-lg" %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :duration, :placeholder => "Durée de la vidéo (en seconde)", class: "form-control input-lg" %>
      </div>
    </div>

  </div>
<br>
  <div class="form-actions">
    <%= f.submit "Ajouter la leçon", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="no-top-image col-md-8 col-md-offset-2">
	<div class="panel panel-default">
		<div class="panel-body">
			<h2 class="page-header text-center">Modifier la leçon</h2>
<%= render 'form' %>

</div>
</div>
</div>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Nr</th>
      <th>Video</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.nr %></td>
        <td><%= lesson.video %></td>
        <td><%= lesson.course_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<div class="no-top-image col-md-8 col-md-offset-2">
	<div class="panel panel-default">
		<div class="panel-body">
			<h2 class="page-header text-center">Ajouter une nouvelle leçon</h2>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/lessons/show.html.erb
<% content_for :title do %>
Hackuna | <%= @lesson.name %>
<% end %>

<div class="course_title">
  <div class="text-right">
    Le cours : <%= link_to @lesson.course.name, course_path(@lesson.course) %>
  </div>
</div>

<h1 class="page-header text-center">
  <div class="row">
    <div class="col-md-3">
  <!-- previous lesson -->
  <%= link_to "< Leçon précédente", lesson_path(@lesson.previous), class: "btn btn-link pull-left" if @lesson.previous %>
</div>

  <!-- title -->
  <div class="col-md-6">

  <%= @lesson.name %>
</div>
  <!-- achived and next -->
<div class="col-md-3">
  <% if current_user.has_achieved?(@lesson) %>


    <%= link_to "Leçon suivante >", lesson_path(@lesson.next), class: "btn btn-link pull-right" if @lesson.next %>
  <% else %>

    <%= simple_form_for(@achievement) do |f| %>
      <%= f.error_notification %>

        <%= f.hidden_field :achievable_type, value: "Lesson" %>
        <%= f.hidden_field :achievable_id, value: @lesson.id %>

        <% if @lesson.next %>
        <%= f.submit "J'ai compris ! >", class: "btn btn-primary pull-right" %>
        <% else %>
        <%= f.submit "J'ai compris !", class: "btn btn-primary pull-right" %>
        <% end %>
      
    <% end %>
  <% end %>
</div>
</div>
</h1>

<div class="video_background">
  
  <div class="embed-responsive embed-responsive-16by9">
  <%= @lesson.video_html %>
  </div>

</div>


<div class="col-md-8 col-md-offset-2">
<div class="text-center">
  <!-- achived and next -->

  <% unless current_user.has_achieved?(@lesson) %>

    <%= simple_form_for(@achievement) do |f| %>
      <%= f.error_notification %>

        <%= f.hidden_field :achievable_type, value: "Lesson" %>
        <%= f.hidden_field :achievable_id, value: @lesson.id %>

        <% if @lesson.next %>
        <%= f.submit "J'ai compris ! Je passe à la leçon suivante >", class: "btn btn-primary btn-lg btn-block" %>
        <% else %>
        <%= f.submit "J'ai compris !", class: "btn btn-primary btn-lg btn-block" %>

        <% end %>
      
    <% end %>
  <% end %>
  </div>


<!--<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p> -->

<h2 class="page-header">
  Notes
  
</h2>

<% @lesson.notes.each do |note| %>
<p>
  <%= markdown(note.content) %>
</p>
<% end %>


<% if current_user == @lesson.course.teacher %>
<hr>

  <div class="panel panel-default">
    <div class="panel-body">


      <%= simple_form_for(@note) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :content,  :label => "Ajouter une note", :input_html => {:rows => 5, :placeholder => "Ajouter le contenu de la note", class: "form-control", :data => {:provide => "markdown"} } %>
          <%= f.hidden_field :lesson_id, value: @lesson.id %>
        </div>

        <div class="form-actions">
          <%= f.submit "Ajouter la note", class: "btn btn-primary btn-lg btn-block" %>
        </div>

      <% end %>
    </div>
  </div>


<% end %>

</div>

  