config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :achievements
  resources :notes
  resources :lessons
  resources :courses
  resources :charges

  authenticated :user do
    #root to: 'courses#index', :as => "authenticated_root"
    #in the meantime, a welcome route
    root to: 'courses#index', :as => "authenticated_root"
  end

  root to: 'visitors#home'
  
  devise_for :users
  resources :users

  get "about" => "visitors#about"

  #in order to make stripe work
  post '/buy/:id', to: 'charges#create', as: :buy
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default text-center footer-nav" role="navigation">

    <br>
      <p>Hackuna by Etalyo | copyright 2015 - 2018
      </p>

    <span class="fa-stack fa-lg">
		<a href="http://facebook.com/hackuna.academy" target="_blank">
		  	<i class="fa fa-circle fa-stack-2x hkncolor"></i>
		  	<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
		</a>
	</span>

	<span class="fa-stack fa-lg">
		<a href="http://instagram.com/hackuna.academy" target="_blank">
		  	<i class="fa fa-circle fa-stack-2x hkncolor"></i>
		  	<i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
		</a>
	</span>

	<span class="fa-stack fa-lg">
		<a href="mailto:contact@hackuna.academy" target="_blank">
		  	<i class="fa fa-circle fa-stack-2x hkncolor"></i>
		  	<i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
		</a>
	</span>


      
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <!--<li><%= link_to 'Connexion', new_user_session_path %></li>
  <li><%= link_to 'Inscription', new_user_registration_path %></li>-->
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Hackuna', root_path, class: 'navbar-brand whitey homebrand hackunafont' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--<li><%= link_to 'Cours', courses_path %></li>-->
<!--<li><%= link_to 'About', about_path %></li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hackuna | Cours en ligne" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hackuna est un concentré de tout ce que j'aurais voulu savoir il y a quelques années, avant d'entamer mon aventure entrepreneuriale tech. Ou comment générer des revenus, sans capital de départ." %>">
    <meta name="keywords" content="cours, online, web development, entrepreneuriat, entrepreneurship, ruby on rails, code, learn, marketing, startup, business, bootstrap">

    <meta property="og:title" content="<%= yield(:title).present? ? yield(:title) : "Hackuna | Cours en ligne" %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.url %>" />
    <meta property="og:image" content="<%= content_for?(:fb_image) ? yield(:fb_image) : "http://hackuna.org/assets/hkn-94056df39504405aca6e4377952d37e5d0c862e1f26ebdd8261e28d8dca96d29.png" %>" />
    <meta property="og:site_name" content="Hackuna.org" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>
    

        <% if user_signed_in? %>
<main role="main">

  
      <div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand whitey">
                
                    <%= link_to "Hackuna", root_path, class: "sidebar_brand hackunafont" %>
                
            </li>
            <li>
                <%= link_to "Votre compte", user_path(current_user) if current_user %>
            </li>
            <!--
            <% Course.all.each do |course| %>
                <li><%= link_to truncate(course.name, length: 20), course %></li>
            <% end %>
            
            <hr>
            <li>
                <a href="#">Inviter des amis</a>
            </li>
            <li>
                <a href="#">Poser une question</a>
            </li>
            <hr>
            <li>
                <a href="#"><%= link_to "A propos", about_path %></a>
            </li>-->
            <li>
                <a href="#">
                    <li><%= link_to 'Se déconnecter', destroy_user_session_path, :method=>'delete' %></li>
                </a>
            </li>
            <hr>
            <div class="text-center">
                <a href="#">
                    <i class="fa fa-facebook fa-lg fa-inverse"></i>
                </a> | 
                <a href="#">
                    <i class="fa fa-twitter fa-lg fa-inverse"></i>
                </a> | 
                <a href="#">
                    <i class="fa fa-envelope fa-lg fa-inverse"></i>
                </a>
            </div>
        </ul>

    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="top-image">
        <%= yield :image %>
        <div class="page_title">
           
                    <%= yield :page_title %>
                
        </div>
        <a href="#menu-toggle" class="btn btn-primary btn-sm" id="menu-toggle">
          <i class="fa fa-bars fa-lg"></i>
        </a>
      </div>
        <div class="container-fluid">
            
                    
                    
<br>
                    <%= render 'layouts/messages' %>
                    <%= yield %>
                 
            </div>
        
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>
</main>
<% else %>
    <%= render "layouts/navigation" %>
    
    <div class="top-image-unlogged">
        <%= yield :image %>
        <div class="page_title_unlogged">
            <%= yield :page_title %>
        </div>
    </div>
    
        <%= yield %> 
    

<% end %>

  
    
</body>

<% unless user_signed_in? %>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
  <% end %>

</html>